/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dagger.basic

import dagger.Component
import javax.inject.Inject


class Keyboard @Inject constructor()

class Speaker @Inject constructor()

class Computer @Inject constructor(
    val keyboard: Keyboard,
    val speaker: Speaker,
)

@Component
interface AppComponent {
    fun getComputer(): Computer
}

// run project with ./gradlew run
fun main() {
    val appComponent: AppComponent = DaggerAppComponent.create()
    val computer: Computer = appComponent.getComputer()
}